
###
GET {{auth_host}}/auth/oauth/authorize?client_id=XcWebApp&response_type=code&scope=all&redirect_uri=http://www.51xuecheng.cn

### 获取code
GET http://localhost:63070/auth/oauth/authorize?client_id=XcWebApp&response_type=code&scope=all&redirect_uri=http://www.51xuecheng.cn

# http://www.51xuecheng.cn/?code=1O5xYl

### 授权码模式
### 第一步申请授权码(浏览器请求)/oauth/authorize?client_id=c1&response_type=code&scope=all&redirect_uri=http://www.51xuecheng.cn
### 第二步申请令牌
POST {{auth_host}}/auth/oauth/token?client_id=XcWebApp&client_secret=XcWebApp&grant_type=authorization_code&code=UqBmZ1&redirect_uri=http://www.51xuecheng.cn

#{
#  "access_token": "955e450b-5979-40db-8c3c-9e76bd121464",
#  "token_type": "bearer",
#  "refresh_token": "e55ecd5f-2e1b-40db-ab37-47d1eb21963a",
#  "expires_in": 7161,
#  "scope": "all"
#}


### 密码模式(普通加密)
POST {{auth_host}}/auth/oauth/token?client_id=XcWebApp&client_secret=XcWebApp&grant_type=password&username=zhangsan&password=123
#{
#  "access_token": "955e450b-5979-40db-8c3c-9e76bd121464",
#  "token_type": "bearer",
#  "refresh_token": "e55ecd5f-2e1b-40db-ab37-47d1eb21963a",
#  "expires_in": 7099,
#  "scope": "all"
#}


### 密码模式(jwt加密)
POST {{auth_host}}/auth/oauth/token?client_id=XcWebApp&client_secret=XcWebApp&grant_type=password&username=zhangsan&password=123

#{
#  "access_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsieHVlY2hlbmctcGx1cyJdLCJ1c2VyX25hbWUiOiJ6aGFuZ3NhbiIsInNjb3BlIjpbImFsbCJdLCJleHAiOjE2OTE5NDExNTUsImF1dGhvcml0aWVzIjpbInAxIl0sImp0aSI6IjI5NDUwOGZiLTljYmEtNDAxZS1iMDNhLTRjYzFjYmFiZTBhNiIsImNsaWVudF9pZCI6IlhjV2ViQXBwIn0.Tv7RHqTU9gMChfwjcx1IKxogB9hse9eJL9mYU74bCEU",
#  "token_type": "bearer",
#  "refresh_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsieHVlY2hlbmctcGx1cyJdLCJ1c2VyX25hbWUiOiJ6aGFuZ3NhbiIsInNjb3BlIjpbImFsbCJdLCJhdGkiOiIyOTQ1MDhmYi05Y2JhLTQwMWUtYjAzYS00Y2MxY2JhYmUwYTYiLCJleHAiOjE2OTIxOTMxNTUsImF1dGhvcml0aWVzIjpbInAxIl0sImp0aSI6IjdhMmEyYzU4LWZjMDEtNGQwNS05NDc2LTQ5NDM2ODU2N2NhOSIsImNsaWVudF9pZCI6IlhjV2ViQXBwIn0._wqalLITzirfbyoNQt-1tvXEGL9d01x85Bq1F-AjHlU",
#  "expires_in": 7199,
#  "scope": "all",
#  "jti": "294508fb-9cba-401e-b03a-4cc1cbabe0a6"
#}
#Response file saved.
#> 2023-08-13T213916.200.json
#
#Response code: 200; Time: 2223ms (2 s 223 ms); Content length: 813 bytes (813 B)

### 校验jwt令牌
POST {{auth_host}}/auth/oauth/check_token?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsieHVlY2hlbmctcGx1cyJdLCJ1c2VyX25hbWUiOiJ7XCJiaXJ0aGRheVwiOlwiMjAyMi0wOS0yOFQxOToyODo0NlwiLFwiY3JlYXRlVGltZVwiOlwiMjAyMi0wOS0yOFQwODozMjowM1wiLFwiaWRcIjpcIjUwXCIsXCJuYW1lXCI6XCLlrabnlJ8xXCIsXCJuaWNrbmFtZVwiOlwi5aSn5rC054mbXCIsXCJwYXNzd29yZFwiOlwiXCIsXCJzZXhcIjpcIjFcIixcInN0YXR1c1wiOlwiMVwiLFwidXNlcm5hbWVcIjpcInN0dTFcIixcInVzZXJwaWNcIjpcImh0dHA6Ly9maWxlLjUxeHVlY2hlbmcuY24vZGRkZlwiLFwidXR5cGVcIjpcIjEwMTAwMVwifSIsInNjb3BlIjpbImFsbCJdLCJleHAiOjE2OTIwMDI5MTUsImF1dGhvcml0aWVzIjpbInRlc3QiXSwianRpIjoiYTViOWEzZGItMDhhZS00Yzk0LWFmMmUtMjlmZDUxYTVmNTBkIiwiY2xpZW50X2lkIjoiWGNXZWJBcHAifQ.Gy-MtZ_Xfg7FYf1237dQShN9nWm0CClS5Ada7cyyI3Y

#{
#  "aud": [
#    "xuecheng-plus"
#  ],
#  "user_name": "zhangsan",
#  "scope": [
#    "all"
#  ],
#  "active": true,
#  "exp": 1691941155,
#  "authorities": [
#    "p1"
#  ],
#  "jti": "294508fb-9cba-401e-b03a-4cc1cbabe0a6",
#  "client_id": "XcWebApp"
#}
#Response file saved.
#> 2023-08-13T222412.200.json
#
#Response code: 200; Time: 58ms (58 ms); Content length: 184 bytes (184 B)

### 密码模式
POST {{auth_host}}/auth/oauth/token?client_id=XcWebApp&client_secret=XcWebApp&grant_type=password&username=stu1&password=111111

