### 查询课程信息
POST {{content_host}}/content/course/list?pageNo=1&pageSize=2
Content-Type: application/json

{
  "auditStatus": "202004",
  "courseName": "java",
  "publishStatus": ""
}

### 创建课程
POST {{content_host}}/content/course
Content-Type: application/json

{
  "mt": "1-1",
  "st": "1-1-1",
  "name": "JavaScript",
  "pic": "",
  "teachmode": "200002",
  "users": "初级人员",
  "tags": "123",
  "grade": "204001",
  "description": "123",
  "charge": "201000",
  "price": 11,
  "originalPrice":11,
  "qq": "",
  "wechat": "",
  "phone": "",
  "validDays": 365
}